packages:
  - apps/client
  - apps/server
  - libraries/contracts
  - libraries/monitoring
  - libraries/redis
  - providers/idelis
  - providers/flowly
  - providers/gtfs
  - providers/hawk
  - providers/twisto
  - providers/rtm

allowBuilds:
  '@posthog/cli': true
  core-js: false
  esbuild: false
  protobufjs: false
  sharp: false
